#    ___ _             _
#   / __| |_  ___ __ _| |_
#  | (__| ' \/ -_) _` |  _|
#   \___|_||_\___\__,_|\__|
# Author: Christopher Dowell <cbdowell@gmail.com>
#

---
editor: vim

colorize: true

style: monokai

formatter: terminal256

cheatpaths:
  - name: community
    path: ~/.local/share/cheat/community
    tags: [community]
    readonly: true

  - name: dotfiles
    path: ~/.local/share/cheat
    tags: [dotfiles]
    readonly: false
